Repository gbowne1/flickpicker, pull requests merged in 2025-05, with the labels that each got.

#23 Fix#17saving movies
  Backend/app.js
  Backend/client.js
  Backend/controllers.js
  Backend/main.js
  Backend/models.js
  Backend/routes.js
  Backend/server.js
  Data/movieList.json
  Frontend/client/public/index.html
  Frontend/client/public/loadMovies.mjs
  Frontend/client/public/movies.mjs
  Frontend/client/public/script.mjs
Labels: bug, enhancement

#37 fix start script/readme blurb
  Backend/package.json
  README.md
Labels: bug, enhancement, help wanted, good first issue

#36 moving manifest to public static root
  Frontend/client/public/manifest.json
  manifest.json
Labels: enhancement

#24 fixing some paths and the search
  Backend/package.json
  Frontend/client/public/auth.mjs
  Frontend/client/public/index.html
  Frontend/client/public/movies.mjs
  Frontend/client/public/playlist.mjs
  Frontend/client/public/profile.mjs
  Frontend/client/public/script.mjs
  Frontend/client/public/search.mjs
  Frontend/client/public/ytapi.js
Labels: bug, enhancement, help wanted

#45 delete empty files
  Frontend/client/public/app.mjs
  Frontend/client/public/index.mjs
  Frontend/client/public/structured-data.json
Labels: enhancement

#25 Fix movie search functionality (#15)
  Backend/controllers.js
  Backend/server.js
  Frontend/client/public/movies.mjs
  Frontend/client/public/search.mjs
Labels: bug, enhancement, help wanted, good first issue

#30 Fix movies table layout (#14)
  Frontend/client/public/index.html
  Frontend/client/public/loadMovies.mjs
  Frontend/client/public/movies.mjs
  Frontend/client/public/script.mjs
  Frontend/client/public/styles.css
Labels: enhancement, help wanted, good first issue

#34 moved service worker and set scope to root
  Frontend/client/public/script.mjs
  Frontend/client/public/service-worker.js
Labels: enhancement

#35 adding favicons
  Frontend/client/public/assets/logos/android-chrome-192x192.png
  Frontend/client/public/assets/logos/android-chrome-512x512.png
  Frontend/client/public/assets/logos/apple-touch-icon.png
  Frontend/client/public/assets/logos/favicon-16x16.png
  Frontend/client/public/assets/logos/favicon-32x32.png
  Frontend/client/public/assets/logos/favicon.ico
  Frontend/client/public/assets/logos/site.webmanifest
  Frontend/client/public/index.html
Labels: enhancement

#38 making initial movie list load set state.movies
  Data/movieList.json
  Frontend/client/public/loadMovies.mjs
Labels: bug, enhancement

#55 Deleted server.js (#53)
  Backend/server.js
Labels: bug, enhancement

#33 Fixed theme switching logic (#2)
  Frontend/client/public/index.html
  Frontend/client/public/script.mjs
  Frontend/client/public/styles.css
  Frontend/client/public/ui.mjs
Labels: bug, enhancement, help wanted

#56 Added pagination for movies (#41)
  Frontend/client/public/index.html
  Frontend/client/public/movies.mjs
  Frontend/client/public/pagination.mjs
Labels: enhancement

#49 Issue#4 vote count
  Backend/controllers.js
  Backend/routes.js
  Frontend/client/public/auth.mjs
  Frontend/client/public/index.html
  Frontend/client/public/movies.mjs
  Frontend/client/public/script.mjs
Labels: bug, enhancement, good first issue

#54 Uniting of movies/loadMovies.mjs (#47)
  Frontend/client/public/index.html
  Frontend/client/public/loadMovies.mjs
  Frontend/client/public/movies.mjs
  Frontend/client/public/script.mjs
  Frontend/client/public/utils.mjs
Labels: bug, enhancement
